This repo is on exception in python
